Repository Stefouch/sebedius-yearzero-discord-bot, pull requests merged in 2021-07, with the labels that each got.

#115 feat: update v4.0.3-hotfix from master to develop
  CHANGELOG.md
  bot.js
  commands/character.js
  commands/importcharacter.js
  package-lock.json
  package.json
Labels: bug, major

#117 feat: Updated T2k roller for Twilight:2000 V1 new dice mechaincs.
  commands/roll.js
  lang/de.json
  lang/en.json
  yearzero/YZRoll.js
Labels: 🔫 Twilight 2000 4E

#118 feat: v4.1.0
  CHANGELOG.md
  README.md
  commands/roll.js
  lang/de.json
  lang/en.json
  package-lock.json
  yearzero/YZRoll.js
Labels: enhancement
