Repository Stefouch/sebedius-yearzero-discord-bot, pull requests merged in 2021-04, with the labels that each got.

#106 Feat/Fix: More locales and german translations
  Sebedius.js
  bot.js
  commands/changelog.js
  commands/character.js
  commands/crit.js
  commands/help.js
  commands/importcharacter.js
  commands/init.js
  commands/journey.js
  commands/monster.js
  commands/ping.js
  commands/roll.js
  commands/rumor.js
  commands/scrap.js
  commands/setconf.js
  commands/star.js
  commands/supply.js
  commands/threat.js
  commands/zonesector.js
  gamedata/alien/star-generator.de.json
  gamedata/alien/star-generator.en.json
  gamedata/fbl/fbr-journeys.de.yml
  gamedata/fbl/fbr-journeys.en.yml
  gamedata/myz/myz-zonesectors.de.yml
  gamedata/myz/rumors.de.json
  gamedata/myz/rumors.en.json
  gamedata/myz/scrap.de.list
  gamedata/myz/scrap.en.list
  gamedata/myz/threats.list.de.json
  gamedata/myz/threats.list.en.json
  generators/ALIENStarGenerator.js
  lang/de.json
  lang/en.json
  lang/locales.js
  test/client.test.js
  utils/Util.js
  utils/embeds.js
  yearzero/YZCombat.js
  yearzero/YZObject.js
  yearzero/YZRoll.js
  yearzero/YZZoneSector.js
  yearzero/models/Weapon.js
  yearzero/models/sheet/BaseSheet.js
  yearzero/models/sheet/Character.js
  yearzero/models/sheet/parsers/LasseFS.js
Labels: bug, enhancement, lang, minor, ☢️ Mutant Year Zero, ⚔️ Forbidden Lands, 👾 Alien RPG

#109 refactor: getSelection()
  CHANGELOG.md
  Sebedius.js
  commands/attack.js
  commands/character.js
  commands/crit.js
  commands/journey.js
  yearzero/YZCombat.js
  yearzero/YZObject.js
Labels: enhancement

#111 feat: v4.0.2
  CHANGELOG.md
  Sebedius.js
  bot.js
  commands/attack.js
  commands/changelog.js
  commands/character.js
  commands/crit.js
  commands/help.js
  commands/importcharacter.js
  commands/init.js
  commands/journey.js
  commands/monster.js
  commands/ping.js
  commands/roll.js
  commands/rumor.js
  commands/scrap.js
  commands/setconf.js
  commands/star.js
  commands/supply.js
  commands/threat.js
  commands/zonesector.js
  gamedata/alien/star-generator.de.json
  gamedata/alien/star-generator.en.json
  gamedata/fbl/fbr-journeys.de.yml
  gamedata/fbl/fbr-journeys.en.yml
  gamedata/myz/myz-zonesectors.de.yml
  gamedata/myz/rumors.de.json
  gamedata/myz/rumors.en.json
  gamedata/myz/scrap.de.list
  gamedata/myz/scrap.en.list
  gamedata/myz/threats.list.de.json
  gamedata/myz/threats.list.en.json
  generators/ALIENStarGenerator.js
  lang/de.json
  lang/en.json
  lang/locales.js
  package-lock.json
  package.json
  test/client.test.js
  utils/Util.js
  utils/embeds.js
  yearzero/YZCombat.js
  yearzero/YZObject.js
  yearzero/YZRoll.js
  yearzero/YZZoneSector.js
  yearzero/models/Weapon.js
  yearzero/models/sheet/BaseSheet.js
  yearzero/models/sheet/Character.js
  yearzero/models/sheet/parsers/LasseFS.js
Labels: enhancement

#114 feat: v4.0.3 hotfix
  CHANGELOG.md
  bot.js
  package-lock.json
  package.json
Labels: bug, major
